# Generated by Django 5.0.6 on 2024-05-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp1', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(),
        ),
    ]
