# Generated by Django 5.0.6 on 2024-05-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp1', '0006_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
