# Generated by Django 5.0.6 on 2024-05-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp1', '0009_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierating',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movieapp1.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movierating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movieapp1.user'),
            preserve_default=False,
        ),
    ]
