# Generated by Django 5.0.6 on 2024-05-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp1', '0010_movierating_movie_movierating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
